DROP DATABASE IF EXISTS STORYBUILDER;
CREATE DATABASE STORYBUILDER;

USE STORYBUILDER;

INSERT into USERS
(NAME, EMAIL, PASSWORD)
VALUES
('AngelNovo', 'angelnovo15@gmail.com', '$2y$12$ayru4ERyHxT4LrsY1WohXOR59fICyPzaXkVcTDTrL.MAKY25hIvzW');